version: "3.8"
services:
  api:
    container_name: tick-tack-toe-api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5555:5555
    command: npm run start:dev
    env_file:
      - docker.env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12.4
    ports:
      - "5442:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - webnet

networks:
  webnet:
volumes:
  pgdata: